library(dplyr)
library(readr)
library(openxlsx)
library(haven)
library(foreign)
library(labelled)
library(rio)
mcf_data <- read_sav("data/mcf_data_new_reporting_tool.sav")
mcf_data <- characterize(mcf_data)
View(mcf_data$main_activity)
